name: Reusable Build Workflow
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number
        description: "Node.js version to use"
        default: 22
    outputs:
      build-status:
        description: "Status of the build job"
        value: ${{ jobs.build.outputs.build-status }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.set-output.outputs.build-status }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{inputs.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version}}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: set output
        id: set-output
        run: echo "build-status=${{ job.status }}" >> $GITHUB_OUTPUT
