# .github/actions/node-ci-steps/action.yml

name: 'Node.js Project CI Steps'
description: 'Sets up Node.js, installs dependencies, lints, and tests a project'

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: false
    default: '20' # Specify a recent LTS version or your project's requirement

outputs:
  test-summary:
    description: 'A summary of the test execution (e.g., path to results)'
    value: ${{ steps.run-tests.outputs.summary }} # Example: output from test step

runs:
  using: "composite"
  steps:
  - name: Set up Node.js
    uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node-version }}
      cache: 'npm'

  - name: Install Dependencies
    run: npm ci # 'ci' is generally preferred for CI environments for faster, reliable builds
    shell: bash

  - name: Lint Code
    id: lint-code
    shell: bash

  - name: Run Tests
    id: run-tests
    run: |
      if npm test --if-present; then
        echo "Tests passed."
        echo "summary=Test results available." >> $GITHUB_OUTPUT
      else
        echo "Tests failed."
        echo "summary=Tests failed, check logs." >> $GITHUB_OUTPUT
        exit 1
      fi
    shell: bash
