name: Node.js Project CI steps
description: Install the specific Node.js verion, sets up the Node.js dependencies, lints the code, runs tests and builds the project.

inputs:
  node-version:
    description: Node.js version to use
    required: true
    default: '22'

runs:
  using: "composite"
  steps:
  - name: Set up the Node.js version ${{inputs.node-version}}
    uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node-version }}

  - name: Install dependencies
    run: npm ci
    shell: bash
  # - name: Lint the code
  #   run: npm run lint
  #   shell: bash

  # - name: Run tests
  #   run: npm run test
  #   shell: bash

  # - name: Build the project
  #   run: npm run build
  #   shell: bash
