name: Frontend CI

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & Install Deps
        uses: ./.github/actions/setup-node-deps
        with:
          node-version: "22"

      - name: Run Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & Install Deps
        uses: ./.github/actions/setup-node-deps
        with:
          node-version: "22"

      - name: Run Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & Install Deps
        uses: ./.github/actions/setup-node-deps
        with:
          node-version: "22"

      - name: Build Project
        run: npm run build
