name: Output demo
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
    steps:
      - id: step1
        name: Generate output
        run: echo "output1=Hello World" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use output from job1
        run: echo "Output from job1 ${{ needs.job1.outputs.output1 }}"
