name: Reusable Build workflow
on: workflow_dispatch
# This workflow demonstrates how to use reusable workflows for linting, testing, and building a project.
jobs:
  reusable-project-setup:
    uses: ./.github/workflows/reusable-project-setup.yml
    with:
      node-version: 24

  lint:
    needs: reusable-project-setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Lint
        run: npm run lint

  test:
    needs: reusable-project-setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm test

  build:
    needs: reusable-project-setup
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: npm run build
