name: Project Setup Workflow
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number
        description: "Node.js version to use"
        default: 22
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{inputs.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version}}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci
