name: Reusable Build workflow
on: workflow_dispatch
# This workflow demonstrates how to use reusable workflows for linting, testing, and building a project.
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code # <-- Keep this! It's needed for the job to find the reusable workflow file.
        uses: actions/checkout@v4

      - name: Project setup
        uses: ./.github/workflows/reusable-project-setup.yml # Ensure @main or your default branch
        with:
          node-version: "24.x" # It's good practice to pass as a string, e.g., '24.x'

      - name: Run Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint # Good practice to chain jobs
    steps:
      - name: Checkout Code # <-- Keep this!
        uses: actions/checkout@v4

      - name: Project setup
        uses: ./.github/workflows/reusable-project-setup.yml
        with:
          node-version: "24.x"

      - name: Run Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test] # Good practice to chain jobs
    steps:
      - name: Checkout Code # <-- Keep this!
        uses: actions/checkout@v4

      - name: Project setup
        uses: ./.github/workflows/reusable-project-setup.yml
        with:
          node-version: "24.x"

      - name: Build Project
        run: npm run build
