name: Reusable Demo
on: workflow_dispatch
# This workflow demonstrates how to use reusable workflows for linting, testing, and building a project.
jobs:
  call-reusable-build-workflow:
    uses: ./.github/workflows/reusable-build-workflow.yml
    with:
      node-version: 24

  deploy:
    runs-on: ubuntu-latest
    needs: call-reusable-build-workflow
    steps:
      - name: Deploy Application
        run: echo "Deploying application... ${{needs.call-reusable-build-workflow.outputs.build-status}}"
